Update workflows and dependencies for improved validation and linting
- Set 'requirements' in build-sphinx-docs.yaml to optional
- Update output redirection syntax in cla-check.yaml, sphinx-docs.yaml, and track-review-project.yaml for consistency
- Add Actionlint, Zizmor, and Markdown Lint steps to validate workflows in validate.yaml
- Change shell from Python to Bash in labeler action for input validation
- Update pyproject.toml to include new dependencies and configure Markdown Lint settings
- Improve formatting and clarity in README.md

diff --git a/labeler/action.yaml b/labeler/action.yaml
--- a/labeler/action.yaml
+++ b/labeler/action.yaml
@@ -35,15 +35,14 @@ runs:
   using: composite
   steps:
     - name: Validate inputs
-      shell: python
+      shell: bash
       env:
         ACTION: ${{ inputs.action }}
       run: |
-        import os
-        action_opts = ["remove", "add"]
-        action = os.environ["ACTION"]
-        if action not in action_opts:
-            raise ValueError(f"Action has to be one of {action_opts}.")
+        if [[ "$ACTION" != "remove" && "$ACTION" != "add" ]]; then
+          echo "::error::Action has to be one of ['remove', 'add']."
+          exit 1
+        fi
 
     - name: Remove label `${{ inputs.label }}` from issue ${{ inputs.issue }}
       if: ${{ inputs.action == 'remove' }}
